### ISSUE TITLE
Coloring the `Sheet` background rather than replacing it with a flat color

### ISSUE THREAD

**Issue by bananarama92** [dDeepLb/Themed-BC#8]
Heya! I was wondering if you had considered coloring the `Sheet` background, rather than just straight up replace it with a flat color. Did some trial-and-error earlier with `multiply`-based blending and got some pretty good results in combination with a `DrawRoomBackground()` hook:

![blue_da_ba_dee](https://github.com/dDeepLb/Themed-BC/assets/105885570/255c58ab-7726-4b07-b0f0-c8359df65e99)

```ts
const MOD_API: ModSDKModAPI;

MOD_API.hookFunction("DrawRoomBackground", 0, ([URL, ...args], next) => {
    next([URL, ...args]);
    if (URL.includes("Sheet.jpg")) {
        MainCanvas.globalCompositeOperation = "multiply";
        const color = "lightblue"
        DrawRect(0, 0, 2000, 1000, color);
        MainCanvas.globalCompositeOperation = "source-over";
    }
});
```

**Comment by dDeepLb** [comment]
Oh, well wow. I wanted to do this from the start, when mod was an idea, but unfortunately I was too lazy back then to figure out for to do that properly. So as a result I just replaced it with flat color. Now I want to implement it^^
Will add option to choose between flat color and colored sheet. (At first I didn't even understand what you did want from me. Sleep is important~)

Thank you!

**Comment by dDeepLb** [comment]
Also, I suppose that's how icons can be colorized? Because now it does.. well, bad things.. needed to cache colorized icons to make FPS more stable...

**Comment by bananarama92** [comment]
> Also, I suppose that's how icons can be colorized?

Could be? Haven't looked at the implementation here, though I'm wondering if this would not be overkill since with normal BC buttons you can directly specify the background color anyway, no?

**Comment by dDeepLb** [comment]
Yep, you're right, you can specify bg color, but some icons have white filling or outline, white color in general. So here I was getting icons that needed to be colorized, was colorizing them (every frame at first), then caching and using colorized ones.
